In [8]:
import duckdb
con = duckdb.connect()

HYG = 'C:/Users/henry/quant_data/tick_data_storage/HYG/parquet/training_data/*.parquet'
TLT = 'C:/Users/henry/quant_data/tick_data_storage/TLT/parquet/training_data/*.parquet'

con.sql("SET TimeZone = 'UTC'")

┌─────────┐
│ Success │
│ boolean │
└─────────┘
  0 rows

In [ ]:
# 01_profile.sql
con.sql("""
    SELECT DUSTINCT filename
    FROM read_parquet('C:/Users/henry/quant_data/tick_data_storage/*/parquet/training_data/*.parquet', filename=true)
    LIMIT 5
""").df()

,timestamp,price,size,exchange,filename
0,2021-01-04 09:27:26.263294,87.64,100.0,P,C:/Users/henry/quant_data/tick_data_storage/HY...
1,2021-01-04 09:35:25.597938,87.50,60.0,P,C:/Users/henry/quant_data/tick_data_storage/HY...
2,2021-01-04 09:37:28.733121,87.62,7.0,P,C:/Users/henry/quant_data/tick_data_storage/HY...
3,2021-01-04 09:37:29.103615,87.61,7.0,P,C:/Users/henry/quant_data/tick_data_storage/HY...
4,2021-01-04 09:37:33.239229,87.62,7.0,P,C:/Users/henry/quant_data/tick_data_storage/HY...

In [ ]:
# 02_clean.sql

In [ ]:
# 03_zscore.sql